### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by phlppschrr** [ryancramerdesign/FieldtypeMapMarker#13]
I am just posting it here so it doesn't get forgotten, 'John the Painter' [mentioned it already on the forum](https://processwire.com/talk/topic/9711-map-marker-map/?page=15#comment-123084):
> As per Google recent announcement, usage of the Google Maps APIs now requires a key. I've tried to use @ryan's Map Marker (Google Maps) but it errors out due to this. I would assume the module needs updating to allow for an API key field?

**Comment by trk** [comment]
Added pull request for this issue : https://github.com/ryancramerdesign/FieldtypeMapMarker/pull/14

If you want, you can apply my changes to your files or you can directly download applied version.
