### ISSUE TITLE
round(): Argument #1 ($num) must be of type int|float, string given with PHP8

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/FieldtypeMapMarker#25]
It's impossible to save a page with a MM field in PHP 8 because of this error:

![image](https://user-images.githubusercontent.com/871211/109426911-cdd7c700-79a4-11eb-8ddd-ab1cbf739b8e.png)

**Comment by cb2004** [comment]
@adrianbj @ryancramerdesign same issue, I am also wondering why the decimal places are limited to 4 anyway?

**Comment by adrianbj** [comment]
@cb2004 - strange thing is that I can't seem to reproduce this anymore. I've tried googling to see if more recent versions of PHP8 have relaxed this or not, but haven't found anything yet.

Testing via Tracy I see this, so it's like it doesn't care about it being a string anymore - I'm confused :)

![image](https://user-images.githubusercontent.com/871211/124141642-6c9d2e80-da3e-11eb-93e5-24e85b4fc60e.png)

**Comment by andoro** [comment]
I got the same error now.

My PHP version is 8.0.14
ProcessWire version is 3.0.192
Map Marker is 2.0.9

Do you need any additional info regarding the issue? 

![image](https://user-images.githubusercontent.com/775765/148708399-4c453702-6d68-4657-8902-76c48a2bff73.png)

**Comment by craigrodway** [comment]
Changing the code to explicitly cast the values worked for me:

```php
$lat = (float) $input["_{$name}_lat"];
$lng = (float) $input["_{$name}_lng"];

$precision = 4; 
$this->defaultLat = (float) $this->defaultLat;
$this->defaultLng = (float) $this->defaultLng;

if(	((string) round($lat, $precision)) != ((string) round($this->defaultLat, $precision)) ||
```

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update that uses @craigrodway suggestion and also updated the module to be PW 3.x native. Though haven't been able to test properly as my previous maps API keys don't seem to work anymore and Google is asking me for money to get a new key. Can anyone with a key confirm that this update fixes the issue?

**Comment by cb2004** [comment]
@ryancramerdesign the issue seemed to just disappear for me if I remember correctly. With the API, you just supply credit card details and it will only charge if you go over the free uses per month (which is quite a lot).
